apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: demo-client-learning
  namespace: kong-learning
  annotations:
    kubernetes.io/ingress.class: kong
username: demo-client-learning
