apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kong-gateway
  namespace: kong
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: kong
      app.kubernetes.io/component: app
