apiVersion: v1
data:
  handler.lua: |
    local RequestHeaderValidator = {
      PRIORITY = 900,
      VERSION = "1.0.0",
    }

    function RequestHeaderValidator:access(conf)

      local header_value =
        kong.request.get_header(conf.header_name)

      if not header_value then
        return kong.response.exit(
          conf.status_code,
          {
            message = "Required request header is missing",
            header = conf.header_name
          }
        )
      end

      kong.service.request.set_header(
        "X-Header-Validated",
        "true"
      )
    end

    return RequestHeaderValidator
  schema.lua: |
    local typedefs = require "kong.db.schema.typedefs"

    return {
      name = "request-header-validator",

      fields = {
        {
          consumer = typedefs.no_consumer
        },

        {
          protocols = typedefs.protocols_http
        },

        {
          config = {
            type = "record",

            fields = {
              {
                header_name = {
                  type = "string",
                  required = true,
                  default = "X-Client-ID",
                }
              },

              {
                status_code = {
                  type = "integer",
                  required = true,
                  default = 400,
                  between = { 400, 499 },
                }
              }
            }
          }
        }
      }
    }
kind: ConfigMap
metadata:
  name: request-header-validator
  namespace: kong
