gateway:
  image:
    repository: ghcr.io/merazsheikh/kong-request-header-validator
    tag: kong-plugin-v1.0.0
    effectiveSemver: "3.9.3"
    pullPolicy: IfNotPresent

  plugins:
    configMaps: []

  env:
    plugins: bundled,request-header-validator
